version: 2
jobs:
  build_2_1:
    working_directory: /checkout
    docker:
      - image: temochka/cblite-test:2.1
    steps:
      - checkout
      - run: bundle install -j2
      - run: bundle exec rspec
  build_2_2:
    working_directory: /checkout
    docker:
      - image: temochka/cblite-test:2.2-dev
    steps:
      - checkout
      - run: bundle install -j2
      - run: bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - build_2_1
      - build_2_2
